name: Caller Workflow

on:
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
        - uses: peter-evans/repository-dispatch@v1
          with:
            token: ${{ secrets.TOKEN }}
            event-type: MyEvent
            client-payload: '{"paramA": "123"}'