name: Install Dependencies

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      run: npm install
        working-directory: ./node-app
      - run: npm run build --if-present
      - run: npm test